import Providers from './providers'
import type React from 'react'
import type { Metadata } from 'next'
import "./globals.css";
import {NavBar} from "@/components/nav-bar";
import {LCPMonitor} from "@/components/perf/LCPMonitor";
import {NavHoc} from "@/components/nav-hoc";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: {
  children: React.ReactNode
}) {
  const IsAdminNavBar = NavHoc(NavBar)
  return (
    <html lang="en">
      <body>
        <Providers>
          <IsAdminNavBar options={[{name:'HOC权限',href:'/pokemon'}]} />
          {children}
        </Providers>
        <LCPMonitor/>
      </body>
    </html>
  )
}